### ISSUE TITLE
Is it usable in prod?

### ISSUE THREAD

**Issue by Madi-S** [blokje/aiobcrypt#9]
Does anyone have experience using this package along with fastapi in production? Does it affect the app flow in any way by instantiating a new `ThreadPoolExecutor`?

**Comment by blokje** [comment]
Actually, I've build this to pull out the authentication flow of the main loop in FastAPI. This greatly improved authentication flow while also mitigating a Denial-Of-Service on other endpoints due to invalid login attempts. This is a technique used by multiple other projects (such as SqlAlchemy for example) to make synchronous code run async.
